### ISSUE TITLE
RuntimeError: Invalid interval bounds!

### ISSUE THREAD

**Issue by mzytnicki** [ykai16/DARIC#1] opened 2023-11-28 13:41 UTC
First, let me thank you for your tool.

I would like to use DARIC, but end up with the following error: `RuntimeError: Invalid interval bounds!`

This error is triggered by `lib/calculation.py`, at line

    pc1value = pc1bw.stats(chrom, i*reso, i*reso+reso, type='mean')[0]
 
I added some log in the file, and this is probably caused by an "uncomplete" bw file.
In fact, the bedgraph file produced by HOMER (which I converted to bw afterwards) does not include all bins.
For instance, in my case (mm10), the first line of this file is

    chr1       3000000 3100000 -0.030277508204277

The first bins are missed, probably because of telomeric repetitions.

Now, DARIC fails when considering this bin (actually, it changes at each execution, which surprised me):

    chr1 195100000 195200000

Of note, the `chromSizes` value for `chr1` is 195471971

The last line of chr1 in my bedgraph is:

    chr1       194900000       195000000       -0.968380206916893

Since the bedgraph does not reach position 195471971, it fails (this is what I assume).

Would it possible to fix this? For instance, by setting a default value of the pc1bw by default of `0` of for the whole `chromSizes`?

Thanks!

**Comment by ykai16** [comment] 2023-11-29 05:54
Thank you for using DARIC and reporting the issue. 

Would you mind to share the PC1 files (bigwig and bedgraph) you used with me? I will look into this and fix the issue ASAP.

**Comment by mzytnicki** [comment] 2023-11-29 07:46
Sure!
You can find the files here: https://filesender.renater.fr/?s=download&token=364f6db1-fe23-443e-8d4f-b0f91be9ae06
They will be available for a week or so.
Thanks!

**Comment by ykai16** [comment] 2023-12-02 06:55
Hi, just fixed this issue and pushed a new version to PyPI. Please uninstall the current version and then reinstall the package using pip. Let me know if the problem is still around.

I am closing the issue now. Feel free to reopen it if it does not work.

**Closed as completed** 2023-12-02 06:55 UTC
